# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fb5415dc594ea101fa505688821c5cbbdadd8cb5f7ad2b9f7a75374b73f200e8767d7226885b504a7889e8e905890eb8fc11b53c7d89ae93361a5a336a428076

test:
  secret_key_base: 15743315c3f8922d7c5735492b54c2318a0f659b5de80c2bc91ec2caffc17236fe62e7783171291a7e7506ab4a3f2b9fc60bc6b47f0986446a59527cd5fb702c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
