# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 845669c2b30c1a868fde07bd2a92bbc7f2595caade2cc6549b7a30055865d25546b8ab4f6de1245c5ee403d52dd1195f47758f14f6fd58b7b7edb9645e802caf

test:
  secret_key_base: d86621ba7cb46146ca7ea73ad1ba40f5b89265a13b774164886ed15cbbaab71d2d088e6550b6b1cad0a860b5cc42575cf633cca5c9f1ac920aa2218942d6d882

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
